### ISSUE TITLE
Rely on Composer instead of Git submodule feature

### ISSUE THREAD

**Issue by bgatellier** [mailin-api/sendinblue-api-bundle#1]
Hi,

First of all thank you for this bundle :)

I just added this bundle to my Symfony (latest 2.7-dev version) using Composer.
I was expecting to commit the files (with Git and TortoiseGit) as usual, from the root folder, but it appears that the bundle comes as a Git submodule.

From what I can read around the web, Composer is the officialway to manage Symfony2 dependencies, [as the french 2.7 doc says](http://symfony.com/fr/doc/2.7/cookbook/workflow/new_project_git.html#vendors-et-submodules) (the english one does not mention it).
So instead of relying on the submodule feature, I would suggest to rely on Composer in order to avoid a messy bundle management. That's what most Symfony2 bundles already do.

Hope I was clear enough in my explanations,

**Comment by ekta-slit** [comment]
Hello,

Thank you for your message.
We have fixed the issue and commited the new change.

You can re-download the bundle to continue the services.

Regards,
Sendinblue
