### ISSUE TITLE
Bug SSL Certificate

### ISSUE THREAD

**Issue by alidevweb** [mailin-api/sendinblue-api-bundle#12]
Disable SSL verification, when I used this bundle without having an ssl certificate it doesn't work. So disabling  SSL verification will work in both cases.
In the "Wrapper/Mailin.php", just after:
 CURLOPT_TIMEOUT_MS => $this->timeout,
I added this two lines:
 CURLOPT_SSL_VERIFYHOST => false,
 CURLOPT_SSL_VERIFYPEER => false,
And it worked for me, so, can you add this two lines in the master brach.

Thanks

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-symfony-bundle
