### ISSUE TITLE
Problem with function sendTransacEmail()

### ISSUE THREAD

**Issue by ghost** [mailin-api/sendinblue-api-bundle#14]
Hello,

I have a problem when i want to use the function sendTransacEmail().

I obtain this error : Attempted to call an undefined method named "swaggerFormats" of class "Symfony\Component\HttpFoundation\Response".

Here my code that obtain this :

$api_instance = new \SendinBlue\Client\Api\SMTPApi();
$sendSmtpEmail = new \SendinBlue\Client\Model\SendSmtpEmail();
$sender = new \SendinBlue\Client\Model\SendSmtpEmailSender();
$sender->setName($revue->getConfig()->getLibelleExpediteur());
$sender->setName($revue->getConfig()->getEmailExpediteur());
$To = new \SendinBlue\Client\Model\SendSmtpEmailTo();
$To->setEmail($Contact->getEmail());
$sendSmtpEmail->setSubject("Merci pour votre accueil téléphonique");
$sendSmtpEmail->setHtmlContent($html);
$result = $api_instance->sendTransacEmail($sendSmtpEmail);

Thanks

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-symfony-bundle
