### ISSUE TITLE
replyto not working with send_transactional_template

### ISSUE THREAD

**Issue by beyondsagency** [mailin-api/sendinblue-api-bundle#15]
Hello,

I have a problem when i want to add replyto in send_transactional_template.

I know it's not specify in comment on the function : 

    /*
        Send templates created on SendinBlue, through SendinBlue SMTP (transactional mails).
        @param {Array} data contains php array with key value pair.
        @options data {Integer} id: Id of the template created on SendinBlue account [Mandatory]
        @options data {String} to: Email address of the recipient(s). You can use pipe ( | ) to separate multiple recipients. Example: "to-example@example.net|to2-example@example.net" [Mandatory]
        @options data {String} cc: Same as to but for Cc [Optional]
        @options data {String} bcc: Same as to but for Bcc [Optional]
        @options data {Array} attrv The name of attribute present in your SendinBlue account. It should be sent as an associative array. Example: array("NAME"=>"name"). You can use commas to separate multiple attributes [Optional]
        @options data {String} attachment_url: Provide the absolute url of the attachment. Url not allowed from local machine. File must be hosted somewhere [Optional]
        @options data {Array} attachment: To send attachment/s generated on the fly you have to pass your attachment/s filename & its base64 encoded chunk data as an associative array [Optional]
    */

But it's possible in the documentation of sendinblue : https://apidocs.sendinblue.com/fr/template/#1

Thanks

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-symfony-bundle
