### ISSUE TITLE
Integration with the new Symfony Mailer

### ISSUE THREAD

**Issue by erichard** [mailin-api/sendinblue-api-bundle#16]
A new component Symfony Mailer has been created recently. It provide smtp and API transport.

More information on the Symfony PR : https://github.com/symfony/symfony/pull/30741

Do you have any plan for an integration ?

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-symfony-bundle
