### ISSUE TITLE
ClassNotFoundException in Mailin.php

### ISSUE THREAD

**Issue by bgatellier** [mailin-api/sendinblue-api-bundle#3]
Hi,

I've just installed your bundle in a freshly new Sf 2.7 and 2.8-beta1, and it appears that there is an error in the _Maillin_ class: `Attempted to load class "Exception" from namespace "SendinBlue\SendinBlueApiBundle\Wrapper".`
I found out the file and here is the error:

```
if(!function_exists('curl_init')) 
{
    throw new Exception('Mailin requires CURL module');
}
```

So I suggest to add a `use Symfony\Component\Config\Definition\Exception\Exception`.
I'll do a PR for that.

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.

We appreciate your suggestions and merged PR.

Regards,
SendinBlue Team
