### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by bgatellier** [mailin-api/sendinblue-api-bundle#5]
Hi,

Is there an update planned for Symfony 3 ?

**Comment by micari** [comment]
> Hi,
> 
> Is there an update planned for Symfony 3 ?

Hi,
Of course. We'll release it by end of February. Maybe even sooner.

**Comment by micari** [comment]
> Hi,
> 
> Is there an update planned for Symfony 3 ?
> Hi,
> Of course. We'll release it by end of February. Maybe even sooner.

Hi @bgatellier, the bundle as been updated for Sf3 compatibility. Please let us know if any issue.

**Comment by bgatellier** [comment]
Hi,

Thank you for your effort.
Unfortunately, I am unable to download it through composer, whatever the method:
manually update the .json and run a composer update, or directly run composer require.

I tried on a freshly downloaded Sf3 version (3.0.1 at this time)

**Comment by bgatellier** [comment]
I am not a expert using Composer, but I just tried with the [@dev stability flag](https://getcomposer.org/doc/04-schema.md#package-links), and everything is working as expected:
`composer require sendinblue/sendinblue-api-bundle:2.0.*@dev`
I am assuming that this version of the bundle it is still a work-in-progress, so this flag makes sense.

**Comment by micari** [comment]
> I am not a expert using Composer, but I just tried with the @dev stability flag, and everything is working as expected:
> composer require sendinblue/sendinblue-api-bundle:2.0.*@dev
> I am assuming that this version of the bundle it is still a work-in-progress, so this flag makes sense.

Hello @bgatellier,
You're right, 1.0.5 is the last stable release for now.

**Comment by micari** [comment]
> I am not a expert using Composer, but I just tried with the @dev stability flag, and everything is working as expected:
> composer require sendinblue/sendinblue-api-bundle:2.0.*@dev
> I am assuming that this version of the bundle it is still a work-in-progress, so this flag makes sense.

Hello @bgatellier,

sf3 version (2.0.1) is know the latest stable release so you don't need the @dev flag anymore. Please find the documentation here : https://github.com/mailin-api/sendinblue-api-bundle/blob/master/README.md
