### ISSUE TITLE
Send mails through monolog

### ISSUE THREAD

**Issue by benoitproxi** [mailin-api/sendinblue-api-bundle#8]
Hello,

I would like to send emails on critical errors, but I can't figure out how I can achieve that with this bundle.
http://symfony.com/doc/current/logging/monolog_email.html

Is there a way ?

Thank you

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-symfony-bundle
