### ISSUE TITLE
Use models to send data and validate response

### ISSUE THREAD

**Issue by Holicz** [mailin-api/sendinblue-api-bundle#9]
Hello,

I think that instead creating dumb arrays it would be better to set data into an model, then validate it, convert it to array and send it. Why?

1. It is more comfortable for the developer
2. Data validation before making an request to API
3. Unification of work with API

I also sugges to use exceptions when the email was not send so the developer can catch it. It is better way then checking response array itself by the developer.

Also all of this changes might help when the API changes.

I'll do a PR for that.

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-symfony-bundle
